# Generated by Django 4.2.8 on 2023-12-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(default=False, max_length=255, null=True)),
                ('binid', models.CharField(default=False, max_length=255, null=True)),
                ('srcActlocation', models.CharField(default=False, max_length=255, null=True)),
                ('destActlocation', models.CharField(default=False, max_length=255, null=True)),
                ('srcRCSlocation', models.IntegerField(default=0, null=True)),
                ('destRCSlocation', models.IntegerField(default=0, null=True)),
                ('orderstatus', models.IntegerField(default=0, null=True)),
                ('bintransfer', models.BooleanField(default=False, null=True)),
                ('srcrackid', models.IntegerField(default=0, null=True)),
                ('destrackid', models.IntegerField(default=0, null=True)),
                ('binid_status', models.IntegerField(default=0, null=True)),
                ('ord_ack_agv', models.IntegerField(default=0, null=True)),
                ('recived_status', models.IntegerField(default=1, null=True)),
                ('agvstatus', models.IntegerField(default=0, null=True)),
                ('agverror', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.CharField(default=False, max_length=255, null=True)),
                ('date', models.DateField()),
                ('binid', models.CharField(default=False, max_length=255, null=True)),
                ('srcActlocation', models.CharField(default=False, max_length=255, null=True)),
                ('destActlocation', models.CharField(default=False, max_length=255, null=True)),
                ('srcRCSlocation', models.IntegerField(default=0, null=True)),
                ('destRCSlocation', models.IntegerField(default=0, null=True)),
                ('orderstatus', models.IntegerField(default=0, null=True)),
                ('bintransfer', models.BooleanField(default=False, null=True)),
                ('srcrackid', models.IntegerField(default=0, null=True)),
                ('destrackid', models.IntegerField(default=0, null=True)),
                ('binid_status', models.IntegerField(default=0, null=True)),
                ('ord_ack_agv', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
