# Generated by Django 5.0 on 2023-12-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btporders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedata',
            name='binmapping',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='masterdata',
            name='binmapping',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
