# Generated by Django 5.0 on 2023-12-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btporders', '0002_cachedata_binmapping_masterdata_binmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedata',
            name='frontbinpresent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
