# Generated by Django 5.0 on 2024-01-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btporders', '0004_masterdata_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdata',
            name='sample',
        ),
    ]
